// Default imports
import "@/style/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="wrapperTwo">
          <div className="box">
            <div/><div/><div/><div/><div/><div/><div/><div/><div/><div/>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
//{children}
